services:
  nerd-watch:
    image: ghcr.io/avranju/nerd-watch:latest
    container_name: nerd-watch
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
